* Inzhir (October 2019)

* Я — инжир, ты — инжир,
Я проникну в твой эфир,
Ты теперь наполовину кефир, 
Наполовину — рыбий жир,
А я — постмодернизма пассажир,
Социализм порождает транжир, 
Я твоим долбоебизмом не ангажирован,
Да и твой профиль вконтаче низковато ранжирован,
Съел мой панч? Заешь пломбиром!
Свой конец ты найдёшь в кольце Боромира!
На хера ты употребрял бутираты?
Если я теперь всратый, а ты — горбатый,
Накрылась баландой твоя баллада,
Лондон — баба, а у меня с Дорном коллаба,
В дырявое лукошко уложен картофан,
А твоя бабложка обёрнута в салофан,
Я на этой сцене — самодур, признайся, кайся,
Ты зачем трогал мой шампур?!
* ...
* Приятное послевкусие твоего отсутствия,
Будут блоговония, не будет ни благословения, ни напутствия,
Ты танцевал буги-вуги, а я сыпал бисер и ронял домино,
Я залёг в Брюгге, а ты — на экзистенциальное дно в Брно,
У меня что не пословица — то злословица,
Из твоих ран течёт сукровица, а моя хортиця не портится,
На шутки и оскорбления у нас здоровая конкуренция, 
Ты — говяжий башмак, проекция тухлого шницеля, выкидыш брецеля,
На моей стороне аффрикаты и фрикативы,
На твоей — фрикадельки, эпитафии и от шансонье лейтмотивы,
Пока в моём посёлке все напевают “Ёлки”,
В твоём посёлке поотсыхают все весёлки,
Там, где Лысиков заимствовал у Некрасова, 
Там красной нитью бумага лакмусовая,
Я тебе говорю, не стоило брать у страуса образец гипоталамуса,
Орда, легион, леодр, вран, колода,
Джигурда, Фараон, Инсаров Фёдор, Монгол Шуудан, Крид, Кривда, в доме важнее всего погода,
Хоть и тьма тем есть для текстов песен альбома века,
Я выбрал дисс на абстрактного человека
