#+title: Ubuntu 7.04, Пыхтерский Авангард-ADSL, модем D-Link
#+publishDate: <2007-07-21T18:44>
#+tags: avangard d-link ubuntu
#+hugo_section: blog-ru
#+author: Антон Котенко

Вот она, первая статья о невечном :)

На самом деле статей в сети на эту тему много (ну либо они повествуют о
настройке для веб-плюса -- она схожа) -- но результаты у всех разные --
поэтому расскажу свою историю.

подопытные:

- [[http://releases.ubuntu.com/7.04/][Ubuntu 7.40 Feisty Fawn]]
- USB-модем [[http://eciadsl.flashtux.org/modems.php?modem=86][D-Link
  DSL-200 Generation III]]

дополнительные ссылки:

- [[http://starl1te.wordpress.com/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BC%D0%B0-d-link-dsl-200/][Как
  Starl1te настраивал Веб-плюс]]
- [[http://forum.ubuntu.ru/index.php?topic=8712.45][Беседа с человеком у
  которого однажды это всё-таки получилось]]
- [[http://eciadsl.flashtux.org/][Основной источник файлов]]
- [[http://ru.gentoo-wiki.com/ADSL_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BC%D1%8B_%D0%BD%D0%B0_%D1%87%D0%B8%D0%BF%D0%B0%D1%85_GlobeSpan_(D-Link_DSL200)][Как
  это делают в Gentoo]]

#+begin_quote
(дополнительные ссылки также есть в конце статьи)
#+end_quote

Итак, Live/Install CD [[http://releases.ubuntu.com/7.04/][был скачан]]
из интернета, прожжен на болванку и установлен буквально за 10-15 минут,
чем Ubuntu и славится. практически все что нужно обнаружилось и
отдетектилось сразу, за исключением собственно интернета :). сразу
говорю, четких рекомендаций как не было так и нет, насколько я понял у
большинства все "/как-то вышло/" и вполне может быть так, что мой или
чей-то способ может не подойти. у меня, например, интернет пока что
подключается раза с пятого, но хотя бы уже до отключения руками, поэтому
я стараюсь не перезагружаться :). если я найду способы улучшения
ситуации -- я напишу.

Впрочем, меньше прелюдий -- беремся за терминал. Вернее, лучше заранее
достать где-нибудь интернет и скачать вот эту пару файлов: :).

- [[http://eciadsl.flashtux.org/download/debian/etch/eciadsl-usermode_0.11-1_i386_with_synch_patch.deb][ECI-ADSL
  с патчем синхронизации]] (*Upd.*
  [[http://shaman-sir.by.ru/files/eciadsl-usermode_0.11-1_i386_with_synch_patch.deb][альтернативная
  ссылка]])
- [[http://debian.charite.de/ubuntu/pool/universe/r/rp-pppoe/pppoe_3.8-1.1_i386.deb][утилита
  PPPoE]] (или
  [[http://ftp.cica.es/debian/pool/main/r/rp-pppoe/pppoe_3.8-1.1_i386.deb][тут]])
- [[http://eciadsl.flashtux.org/download/eciadsl-synch_bin.tar.bz2][файлы
  синхронизации]] (*Upd.*
  [[http://shaman-sir.by.ru/files/eciadsl-usermode-0.11-synch-patch.tar.bz2][альтернативная
  ссылка]])

С этого момента мы считаем что вы находитесь в той директории, куда вы
положили эти файлы, например =~/Downloads=:

#+begin_example
$ cd ~/Downloads
#+end_example

Одно магическое действие, которое вам скорее всего понадобится для
корректной работы =eciadsl= -- смена среды. Честно говоря я не успел
посмотреть что там было до этого, потому что в =bash= я не
сомневаюсь(лся?), но вероятнее всего на то, как было, если вам будет
надо -- можно будет запросто вернуть командой
=sudo ln -sf /bin/dash /bin/sh=:

#+begin_example
$ sudo ln sf /bin/bash /bin/sh
#+end_example

устанавливаем пакеты:

#+begin_example
$ sudo dpkg -i ./pppoe_3.8-1.1_i386.deb
$ sudo dpkg -i ./eciadsl-usermode_0.11-1_i386_with_sync_patch.deb
#+end_example

распаковываем дополнительные файлы синхронизации и переносим их в
каталог =eciadsl=:

#+begin_example
$ bzip2 -d ./eciadsl-synch_bin.tar.bz2
$ tar -xvf ./eciadsl-synch_bin.tar
$ sudo mv ./eciadsl-synch_bin/*.bin /etc/eciadsl/
$ rm -Rf ./eciadsl-synch_bin
#+end_example

далее, нужно проверить выгружен ли модуль =dabusb=, который по идее и не
должен быть загружен -- в ранних версиях он приводил к ошибкам.

#+begin_example
$ sudo lsmod | grep dabusb
#+end_example

и если он все-таки найдется -- надо его убить, вот так: :)

#+begin_example
$ sudo modprobe -r dabsusb
#+end_example

теперь включаем нужные модули:

#+begin_example
$ sudo modprobe tun
$ sudo lsmod | grep tun
$ sudo modprobe n_hdlc
$ sudo lsmod | grep n_hdlc
#+end_example

сейчас нам нужно узнать /VID/PID/ нашего момеда (насколько я себе
представил --- это код USB-порта на материнской плате, но истинным
знанием я временно не обладаю).

#+begin_example
$ lsusb
#+end_example

там должно быть либо /D-Link/ либо /GlobeSpan/, либо какой-то еще
вариант (если что можно выяснить отключив модем, выполнив =lsusb= и
подключив снова) --- у меня мой модем был в этой строчке:

=Bus 004 Device 006: ID= /=0915:8104=/ =GlobeSpan, Inc.=

выделенные курсивом числа -- и есть /VID:PID/ -- запомните их. Настало
время приступить к конфигурации. можно запустить текстовую версию и
следовать указаниям (пояснения ниже):

#+begin_example
$ sudo eciadsl-config-text
#+end_example

для Авангард-ADSL настройки (примерно :) ) таковы (номера пунктов могут
отличаться):

-
  1) configure all settings
- /юзернейм/пароль/: /ptn///ptn/
- /provider/: (58) Other
- /DNS1/: =213.158.0.6=
- /DNS2/: =213.48.193.36= (на июль 2007 они таковы, в будущем могут
  потенциально поменяться -- следите за новостями Авангарда)
- /VPI/: =0=
- /VCI/: =35=
- /modem/: (16) D-Link DSL200 B1 (засисит от модели вашего модема, но у
  меня кажется не B и работает и я побаиваюсь пока все нестабильно но
  работает тестировать другие варианты :) )
- /VID1/: =__0915__= (первое число из двух, которые показала команда
  =lsusb=)
- /PID1/: =__8104__= (второе число из двух, которые показала команда
  =lsusb=)
- /VID2/: =__0915__= (первое число из двух, которые показала команда
  =lsusb=)
- /PID2/: =__8104__= (второе число из двух, которые показала команда
  =lsusb=)
- /chipset/: (3) =GS7470=
- /SYNCH/: =0= (этот пункт и следующий пункты люди часто ставят наугад,
  я тоже пишу как работает у меня и не знаю почему я это ставил :) )
- /PPPOECI/: =4=
- /=.bin=/ =file=: (18) =/etc/eciadsl/gs7470_synch20.bin= (очень важный
  пункт, на сайте Авангарда пишут использовать именно этот файл , но
  если у вас все еще будут проблемы с синхронизацией -- нужно будет
  перебрать все по одному а в самом худшем случае -- собирать свой)
- /PPP Mode/: (5) =LLC_SNAP_RFC1483_BRIDGED_ETH_NO_FCS= (еще используют
  =LLC_RFC1483_ROUTED_IP=)
- /DHCP/: no
- __Static IP_: no (по дефолту у Авангарда динамический IP, но если у
  вас статический за денюжку то наверное стоит поставить yes :) )

ниже я приведу сам файл =/etc/eciadsl/eciadsl.conf=, который и изменяет
эта утилита --- в том состоянии, в каком он у меня.

далее --- запускаем собственно синхронизацию:

#+begin_example
$ sudo eciadsl-start
#+end_example

тут могут обнаружиться самые обидные проблемы -- если будут ошибки про
_interrupt_ы -- значит вместо первого файла установлена версия без патча
синхронизации и вы меня не слушаетесь :). В моем случае тоже не всё
гладко - первые разы после удачной синхронизации гаснут обе лампочки на
модеме, а среди карт/интерфейсов отстутствует =tap0=:

#+begin_example
$ ifconfig
#+end_example

но раз на пятый-десятый лампочки все-таки не гаснут и тогда хорошо. По
этим причинам я поставил скрипт на автозагрузку, но о нем - ниже. Если
уж совсем много раз не выходит --- что-то не чисто --- проверять
настройки и файлы синхронизации. Вам нужно добиться чтобы лампочки не
гасли :). После этого - набрать:

#+begin_example
$ sudo pppoeconf
#+end_example

это собственно конфигурация =PPPoE=. Утилита должна найти инет на
интерфейсе =tap0= и задавать диалогами вопросы и просьбы, среди которых
попросят ввести пароль/юзернейм снова, а на все остальные - отвечать
разумно, чаще всего -- "да" :).

после этого можно попытаться подключиться:

#+begin_example
$ sudo pppoe-start
#+end_example

и если не =TIMED OUT= а =CONNECT OK= то все замечательно :). желаю чтобы
у вас так и было :).

/P.S. Статья будет исправляться и дополняться/

**** Пояснения:
:PROPERTIES:
:CUSTOM_ID: пояснения
:END:
теперь по поводу гаснущих лампочек. я взял
[[http://starl1te.wordpress.com/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BC%D0%B0-d-link-dsl-200/#comment-52][скрипт
starl1t‘а]], чуток исправил, добавив =pppoe-start= и выставил его в
автозагрузку:

#+begin_src sh

#!/bin/bash

# This is an improved eciadsl launch script, which
# tries to connect after failures until success.
# Feel free to share and modify
# by Starlite

case "$1" in
    start)
        sudo eciadsl-start
        result=$?
        #echo 'exit code:' $result
        until [ $result -eq 0 ]
        do
            echo ‘Error: connection failed’
            sudo eciadsl-stop
            sudo eciadsl-start
            result=$?
        #   echo ‘exit code:’ $result
        done
        echo ‘connection established’
        sudo pppoe-start
        exit $?
        ;;
    stop)
        sudo eciadsl-stop
        exit $?
        ;;
    restart|force-reload)
        $0 stop && $0 start
        exit $?
        ;;
    ,*)
        echo ‘Usage: eciadsl {start|stop|restart}’
        exit 1
        ;;
esac
exit 0
#+end_src

потом - ставим его на автозагрузку:

#+begin_example
$ sudo chmod +x /etc/init.d/eciadsl
$ update-rc.d eciadsl defaults
#+end_example

если нужно - можно запускать его самостоятельно:

#+begin_example
$ sudo /etc/init.d/eciadsl restart
#+end_example

**** Тексты:
:PROPERTIES:
:CUSTOM_ID: тексты
:END:
***** /etc/eciadsl/eciadsl.conf
:PROPERTIES:
:CUSTOM_ID: etceciadsleciadsl.conf
:END:
#+begin_example

VID1=0915
PID1=8104
VID2=0915
PID2=8104
#MODE=LLC_RFC1483_ROUTED_IP
MODE=LLC_SNAP_RFC1483_BRIDGED_ETH_NO_FCS
VCI=35
VPI=0
FIRMWARE=/etc/eciadsl/firmware00.bin
SYNCH=/etc/eciadsl/gs7470_synch20.bin
PPPD_USER=ptn
PPPD_PASSWD=
USE_DHCP=no
USE_STATICIP=no
STATICIP=
GATEWAY=
MODEM=D-Link DSL200 rev B1
MODEM_CHIPSET=GS7470
SYNCH_ALTIFACE=0
PPPOECI_ALTIFACE=1
PROVIDER=Other
DNS1=213.158.0.6
DNS2=213.18.193.36
#+end_example

***** /etc/ppp/pppoe.conf
:PROPERTIES:
:CUSTOM_ID: etcppppppoe.conf
:END:
#+begin_example

ETH='tap0'
USER='ptn'
DEMAND=no
#DEMAND=300
DNSTYPE=SERVER
PEERDNS=yes
DNS1=
DNS2=
DEFAULTROUTE=yes
CONNECT_TIMEOUT=30
CONNECT_POLL=2
ACNAME=
SERVICENAME=
PING="."
CF_BASE=`basename $CONFIG`
PIDFILE="/var/run/$CF_BASE-pppoe.pid"
SYNCHRONOUS=no
#SYNCHRONOUS=yes
CLAMPMSS=1412
#CLAMPMSS=100
#CLAMPMSS=no
LCP_INTERVAL=20
LCP_FAILURE=3
#LCP_FAILURE=30
PPPOE_TIMEOUT=80
FIREWALL=NONE
LINUX_PLUGIN=
PPPOE_EXTRA=""
PPPD_EXTRA=""
#+end_example

**** Примечания:
:PROPERTIES:
:CUSTOM_ID: примечания
:END:

--------------

/от человека, настраивавшего модем ZTE ZXDSL 852, добавляю:/

#+begin_quote
Для модема ZTE ZXDSL 852 нужно еще (кроме драйвера =cxacru.ko=) втыкать
мост =ATM= <-> =ETHERNET= (=PPPoA= <-> =PPPoE=), а для этого ставить
драйвер =br2648.ko= и настраивать через контрольную утилиту =br2684ctl=
(должна входить в пакет =linux-atm-lib= - если нет - можно взять с
[[http://linux-atm.sourceforge.net/][linux-atm.sourceforge.net]]).
#+end_quote

К сожалению ссылка на руководство по сборке файла синхронизации руками
-- периодически умирает :( , если так произошло -- эту статью можно
[[http://www.linuxup.ru/index.php?id=99][найти]] на
[[http://www.linuxup.ru][LinuxUp.Ru]]
([[http://www.linuxup.ru/print.php?id=99][версия для печати]] и
[[http://www.linuxup.ru/index.php?id=100][первая часть статьи]]) или, в
[[http://linux.yaroslavl.ru/docs/conf/hardware/FlashCode.pdf][pdf-версии]]
на [[http://linux.yaroslavl.ru][linux.yaroslavl.ru]]
([[http://64.233.183.104/search?q=cache:CIYtpkx9cj0J:linux.yaroslavl.ru/docs/conf/hardware/FlashCode.pdf+%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE+%D0%BF%D0%BE+%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B5+EciAdsl+%D0%B4%D1%80%D0%B0%D0%B9%D0%B2%D0%B5%D1%80%D0%B0&hl=ru&ct=clnk&cd=1&gl=ru][HTML-версия]]).

И, нашлась еще одна очень неплохая ссылка на
[[http://www.gentoo.ru/?q=node/807][настройку этого дела в Gentoo]], с
использованием ATM. (И еще
[[http://ru.gentoo-wiki.com/ADSL_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BC%D1%8B_%D0%BD%D0%B0_%D1%87%D0%B8%D0%BF%D0%B0%D1%85_GlobeSpan_(D-Link_DSL200)][вот]]
-- о том же но по-другому). И, плюс -
[[http://f0x.ru/wiki/29/249_%CD%E0%F1%F2%F0%EE%E9%EA%E0_Acorp_Sprinter@ADSL_USB_%EF%EE%E4_Ubuntu][ADSL@Ubuntu
& модем ACORP]].

--------------

Для полноты картины нужно на
[[http://forum.runtu.org/index.php?topic=260.0][установку Acorp
Sprinter]] дать ссылку. Там разобрались по-своему.

--------------

Будьте внимательны!

На сайте [[http://eciadsl.flashtux.org/][eciadsl]] убрали версию с
патчем синхронизации. Временно я выложил ее
[[http://rapidshare.com/files/67709667/eciadsl-synch_bin.tar.html][на
rapidshare.com]] и на на
[[http://www.rapidshare.ru/456097][rapidshare.ru]]. Также могу выслать
по почте. Если есть информация, работает ли схема с новой версией (по
слухам - не работает и других схем нет) - прошу поделиться :) .

*Upd.* [[http://forum.ubuntu.ru/index.php?topic=14502.0][Здесь]] у
человека возникла проблема с новым драйвером eciadsl 0.12 на ubuntu
7.10.

И вообще - с опытом выясняется, что модемы D-Link-200 - из ряда тех
вещей, которые если уж достались - то лучше их сразу поменять.

--------------

А
[[http://forum.ubuntu.ru/index.php?topic=14502.msg112057#msg112057][вот
тут]] - про дружбу Ubuntu 7.10 на AMD64, DLink-модема и Авангард ADSL.

--------------

Ещё раз выкладываю eciadsl-0.11, (в том комменте зачем-то выложил файлы
синхронизации):[[http://rapidshare.com/files/77521022/eciadsl-usermode-0.11-synch-patch.tar.bz2.html][.tar.bz2]],
[[http://rapidshare.com/files/77521743/eciadsl-usermode_0.11-1_i386_with_synch_patch.deb.html][.deb]]

[[http://forum.stream.uz/index.php?s=&showtopic=5085&view=findpost&p=340627][Здесь]]
человек настроил всё на 7.10/eciadsl0.10 и довольно подробно описывает
(и там же раньше подробное описание
[[http://forum.stream.uz/index.php?s=&showtopic=5085&view=findpost&p=230190][для
Gentoo]] + решения некоторых проблем).

Сейчас работаю над установкой на 7.04 с ADSL-модемом ZyXEL omni P-630S
EE и eciadsl 0.12.

Отметки:

- действительно, дефолтовый шелл -- =dash=
- утилита конфигурации =eliadsl-config-text= для 0.11 почему-то вылетала
  на вводе логина/пароля ошибку скрипта, поэтому повесил 0.12.
- 0.12 выпадает с ошибкой =double free or courruption= на этапе
  синхронизации, теоретические решения из инета: поставить 0.10 из
  сурсов, скомпилить 0.12 из сурсов,
  [[http://eciadsl.flashtux.org/forum/viewtopic.php?t=3344][использовать
  патч]] (логин/пароль: =eciadsl=/=eciadsl=),
  [[http://eciadsl.flashtux.org/forum/viewtopic.php?t=3358][выбрать
  =RFC_2364=]], проверить все файлы синхронизации...

--------------

/от Анонима:/

Поясню VID - vendor id PID - product id

alt интерфейсы сейчас указаны на flashtux для каждого модема
