#+title: Смесь андрода с носорогом
#+datetime:
#+tags: android rhino javascript
#+hugo_section: blog/drafts

Давно не писал коротеньких статей, да и такие обычно сразу пролистывают
до блоков с картинками и кодом, так что особо распинаться не буду.

В статье показано как прикрутить JavaScript-движок
[[http://www.mozilla.org/rhino/][Mozilla Rhino]] в проект приложения для
[[http://www.android.com/][Google Android]].

- /Почему Rhino?/ Ну, потому что он намеренно предназначен для
  использования в приложениях, пишущихся на Java, а Android --- это,
  похоже, оно такое и есть.
- /Почему JavaScript?/ Ну, он так или иначе сильно засел в повседневной
  жизни современного программиста и если он хочет создать в какой-то
  мере сложную систему, работающую и в вебе и на мобильных платформах, с
  его стороны было мудро написать один общий код и использовать его
  везде. А на каком языке может быть код для нынешнего веба?
- /Почему Android?/ Ну, даже не спрашивайте.

Это всё есть на StackOverflow, я просто зафиксирую.
