* CV: Anton Kotenko

  - E-mail: shaman.sir@gmail.com
  - Location: Munich, Germany
  - Phone: +49 176 84181188
  - [[https://shamansir.github.io][Website]]: https://shamansir.github.io
  - Birthday: 4 March 1984

[[https://github.com/shamansir][GitHub]] -- [[https://stackoverflow.com/users/167262/shaman-sir][StackOverflow]] -- [[https://x.com/shaman_sir][Twitter (X)]] -- [[https://instagram.com/shamansir][Instagram]] -- [[https://soundcloud.com/shamansir][SoundCloud]] -- [[https://vimeo.com/shamansir][Vimeo]] -- [[https://youtube.com/@UlricWilfred][YouTube]] -- [[https://shamansir.bandcamp.com/shamansir][Bandcamp (Artist)]] -- [[https://bandcamp.com/shamansir][Bandcamp (Fan)]] -- [[https://last.fm/shamansir][Last.fm]] -- [[https://livejournal.com/tungusso][LiveJournal]] -- [[https://open.spotify.com/artist/3p5XmmBfQLQkEScwpVdEwU][Spotify (Artist)]] -- [[https://open.spotify.com/user/11125039766][Spotify (Listener)]] -- [[https://www.goodreads.com/user/show/29823581-anton-kotenko][GoodReads]] -- [[https://stepik.org/users/43031759/certificates][Stepik]] -- [[https://codewars.com/users/shamansir][CodeWars]] -- [[https://exercism.org/profiles/shamansir][Exercism]] -- [[https://lanyrd.com/shaman_sir][Lanyrd]] -- [[https://telegram.com/shaman_sir][Telegram]] -- [[https://backloggery.com/shamansir][Backloggery]] -- [[https://infinitebacklog.com/users/shamansir][InfiniteBacklog]] -- [[https://steamcommunity.com/id/shamansir/][Steam]] -- [[https://discord.com/shaman.sir][Discord]] -- [[https://duolingo.com/profile/shamansir][Duolingo]] -- [[https://www.linkedin.com/in/shamansir/][LinkedIn]]

Starting from 2003, I work as a FrontEnd & Software Developer, but that's since even earlier I discovered that developing user interfaces or quite anything visual and interactive, is my passion.
I often preferred programming to gaming or watching TV or going outside (not to the extent, though, or else how would I find friends?).

It is thanks to this feeling of discovering something new and creating something new from the small little logical and mathematical parts, making something beautiful, appealing, friendly, and useful.

So during my work experience I developed many complex components, such as Treemap (or BinPacking) component for monitoring stocks implemented in Delphi, or the interface for Fast Fourier analysis of seismic signal in Borland C++,
or the UI for first neural networks with no more than a dozen layers of neurons, or else your PC take weeks to compute them, then using now-forgotten protocols (e.g. Google Wave aka Federation One) for delivering immersive and friendly chat experience, then it would be JavaScript player for web animation tool Animatron,
and through years it got me into developing generative art with functional programming languages in JetBrains for marketing purposes, so that design team wouldn't be required to manually produce all the variants of art, but just to overlook and rule the generation process.

From all this it could look like I loved mathematics all the way, but at the start I really didn't, and only now I find its laws everywhere around, including music, geometry, or theorem proving.


** Timeline

*** JetBrains GmbH
*FrontEnd & Software Developer*

May 2016 — August 2024

  - [[https://jetbrains.com][jetbrains.com]]
  - [[https://cai.jetbrains.com][Computational Arts Initiative @ JetBrains]]
  - [[https://www.jetbrains.com/lp/devecosystem-2023/][Developers Survey @ JetBrains]]

In JetBrains, I mostly worked in Computational Arts Initiative, which is the team we formed by accident with the designer Serg Golovachev, with whom we've met while working in Animatron.

The purpose of the team is helping designers get rid of the repetitive tasks where marketing requires tons of variations of the same approaches. The technologies differed vastly between projects and years, always it was something with the Web Frontend though.
If you ever used JetBrains IDEs then you there's a chance seen the splash screens produced by us or our folks from the CAI team, after the approve or even polishing by the Design Team, of course, or may be a background of some YouTube video telling your about Tips & Tricks in those IDEs.
You can visit and try web versions of the generators yourself if you follow the link to the CAI below.

Aside from that, I was doing FrontEnd development for jetbrains.com website, some landing pages, or for example, some years of Developers Survey (2017 & 2018) are produced by yours FrontEnd Team representative in collaboration with designers.


  - /Munich/, /Germany/ 

- Technologies: :: JavaScript, React, Elm, HTML5 Canvas, GLSL Shaders, d3.js, Kotlin JS, Kotlin, DHall, PureScript
- Tags: :: #generative-art, #react, #redux, #elm, #dhall, #kotlin-js, #user-interfaces

*** Animatron LLC
*GWT/JS Developer*

July 2011 — May 2016

  - [[https://animatron.com][Animatron Web Editor]]
  - [[https://github.com/Animatron/player][Animatron JS Player @ GitHub]]
  - [[https://animatron.github.io/player/][Animatron JS Player Docs & Sandbox]]

At Animatron, I mostly developed the Web Player based on HTML5 Canvas technology, in pure vanilla JavaScript. Designing a friendly API was one of my tasks, bit not as important as integrating the player into the main GWT-Based Application so that it would reproduce properly and perfectly every feature that the Animation Editor had. That required some GWT coding too. Still, the player also could be used standalone and be embedded into websites, and has a sandbox with the code editor to provide user with an easy way to develop scenes.

  - /Munich/, /Germany/ 2012 — 2016 /(JetBrains GmbH)/
  - /Odessa/, /Ukraine/ 2011 — 2012
  - /Boston/, /United States, MA/ 

- Technologies: :: Java, Google Web Toolkit (GWT), JavaScript, HTML5 Canvas
- Tags: :: #canvas, #javascript, #animation, #gwt, #svg, #graphics

*** iPark Ventures
*GWT Developer*

April 2010 — June 2011

  - [[https://experika.com][Experika]]

Programming and Architecture with GWT ﴾with mvp4g﴿, writing custom components. We developed two web portals: one for job-searchers and HRs, and another one is for pet-owners searching for the medical care or shelter or just to discuss general topics regarding their domestic animals. I am fortunate that the Team-Leads and folks from the company convinced my to give my first public talk on my knowledge which further really helped me in finding next places to work and led to Animatron & JetBrains in the end.

  - /Odessa/, /Ukraine/ 

- Technologies: :: Java, Google Web Toolkit (GWT), mvp4g GWT Framework, JavaScript, Python
- Tags: :: #java, #gwt, #mvp4j, #javascript, #python

*** Exectum LLC
*Java EE / Web Developer*

October 2009 — February 2010

The ExtJS-based FrontEnd for the Administration of a Billing Engine, which communicated to the server using Java-RPC.

  - /St. Petersburg/, /Russia/ 

- Technologies: :: Java, Java RPC, Spring, JavaScript, ExtJS
- Tags: :: #java, #spring, #java-rpc, #ext-js

*** FotoNation / Piclinq
*Java EE Developer*
*JavaScript Web UI Developer*

June 2007 — June 2009

  - [[https://mypicturetown.com][myPictureTown]]

In FotoNation, we developed photo sharing service for Nikon, one of the very first of its kind. At that time, Nikon had released their first Photo Cameras with Wi-Fi support. I worked in the UI Team, responsible both for Java & JavaScript on the FrontEnd, the hardest were the Gallery page and the individual Photo viewer, like including Drag & Drop of images from the file system while there were almost no solutions for it at the time, beating Time Zones and other challenges.

Action System for the UI was the idea and implementation of ours since technologies we used provided no friendly and easy approach. // Development with Apache Wicket + JavaScript ‐ complex native‐JS+Java components and layouting scripts + action system, UI prototypes using JQuery. Components/Layouts are dynamically communicate with server‐side/Database.

  - /St. Petersburg/, /Russia/ 

- Technologies: :: Java, Apache Wicket, Java Server Pages, JavaScript
- Tags: :: #java, #apache-wicket, #javascript, #ajax, #jsp
- 
Recommendations: :: #+BEGIN_QUOTE
Anton is a very talented developer who developed a lot
of Ajax-based Web UI as well as server-side Java code
for myPictureTown service. His knowledge of web technologies and languages, such
as Javascript+Ajax, HTML, CSS are on the expert
level. He is a reliable, hard-working professional, and
I recommend him without reservations. -- Boris Berkman
#+END_QUOTE
#+BEGIN_QUOTE
I know Anton as a brilliant Javascript programmer with strong understanding of the most advanced concepts of this language. His Java skills are also allow him to write good Java code. It is a pleasure to work with such talented professional. -- Sergey Kusnetsov
#+END_QUOTE

*** FK LTD
*Web Developer*

November 2006 — June 2007

CMS Project Development in PHP-JS-CSS for Real Estate Industry; Several small AJAX‐related projects.

  - /St. Petersburg/, /Russia/ 

- Technologies: :: PHP, JavaScript, AJAX, XML
- Tags: :: #ajax, #javascript, #php

*** EmDev LLC
*Software / Web Developer*

March 2005 — October 2006

  - [[https://unlockaustin.com][UnlockAustin]]
  - [[https://emforge.org][EmForge]]

Mostly driven by outsourcing, in this company I participated in J2EE Projects ﴾Spring, Hibernate﴿ from the scratch, writing components, usually trying out and using new technologies
﴾Ajax, JSF, Spring/Hibernate﴿, what used to do before, and keep doing till today. One of the main projects was UnlockAustin, which was a platform for introducing people the musical and theatrical events (but not only those) happening in Austin, Texas.
Could be that Austin is a popular city nowadays due to this web portal :D.
I also developed Delphi Visual Component for Stock monitoring (with realtime/dynamic data visualization support) using TreeMap Algorithm to be integrated into the client desktop application;
Dealing with threads concurrency and a high rate of updates;

  - /St. Petersburg/, /Russia/ 

- Technologies: :: Java, Java EE, Enterprise Java Beans, Java Server Pages, Java Server Faces, Spring, Hibernate, Borland Delphi, Python
- Tags: :: #java, #java-ee, #jsp, #ejb, #jsf, #delphi, #python

*** FSBI "VNII Okeangeologia"
*Software Developer*
*Animation Creator for Conferences*
*Scientific Researcher*
*Interpreter*

March 2003 — March 2005

  - [[https://vniio.ru/about/science_dept/][VNIIO : Science Department]]
  - [[https://www.вниио.рф][The University Website]]

By chance, I got to work at the GeoPhysics University at my age of 19, thanks to the friend. Among the work at the site, we did several travels with camping and monitoring seismic waves in real-time.
The purpose was to predict earthquakes so that people would be aware in advance or would know if it is safe to build bridges at place.
I developed the UI for calculating and configuring Fast Fourier Transform of the raw signal so that significant peaks would be easily noticable on the graphics. At the time I didn't know how significant this algorithm is in almost every technology (like breaking audio into harmonics, actually the same we did here, or converting digital pictures to their vector counterpart keeping almost the perfect representation of the form), but now I do.
Also, it happend that someone noticed I know how to use Macromedia Flash and our Head of Science asked me to provide a friendly and descriptive animation of the tectonic plates colliding for his talks. After all, he invited me to be a guest of his talk with this animation in Arkhangelsk and hired the professional Animator to teach me further.
        

  - /St. Petersburg/, /Russia/ 
  - /Xiao Nang Hai/, /China/ 
  - /Privetnoye/, /Ukraine/ 

- Technologies: :: Borland Delphi, Object Pascal, C++, Assembler, Macromedia Flash
- Tags: :: #animation, #delphi, #macromedia-flash, #asm, #cpp

** Talks

*** The Basics of Generating Everything


in 2023

@ [[https://www.meetup.com/munich-lambda/events/296915834/][Lambda Meetup @ JetBrains ('tail 23)]]. Munich, Germany

How we can use waves a base for generating both audio or static graphics or video or something else, on the example of oscillators, how generic its concept is, and how in the end everything is a wave (and a monad!).

  - [[https://youtu.be/e9urkjHSgXY][Video]]  (EN)

*** PureScript with a chance of Free Monads


in 2023

@ [[https://www.meetup.com/munich-lambda/events/289723656/?eventOrigin=group_past_events][Lambda Meetup @ JetBrains ('head 23)]]. Munich, Germany

This talk describes the use of Free Monad concept in the core of Noodle project of mine. The pros and cons of Free Monads are yet discussed a lot, but in my case they really helped in abstracting concepts while keeping the code user-friendly.

  - [[https://www.youtube.com/watch?v=oSZMB9f6v4c][Video]]  (EN)

*** Noodle : Animation as Ramen


in 2022

@ JetBrains Design Talks '22. Munich, Germany

This talk was recorded during Covid and is about my project Noodle, for visual programming, which is the next version of RPD and now is in the development. The talk was a part of the next iteration of design talks from our company, and company helped a lot in its recording, but its production was finished later and its public promotion was cancelled due to the world-turning event such as declaring war by my own country, so we had no emotional/moral resources as well as reasons to proceed with it.

  - [[https://www.youtube.com/watch?v=FSzMBKYgvCE&list=PLQ176FUIyIUZ3DvECf0NkkOpYwE0JECFn&index=9][Video]]  (EN)

*** Tron : Minimalist UI for Generative Art


in 2020

@ [[https://www.jetbrains.com/lp/designconf/][JetBrains Design Conference '20]]. Munich, Germany

Tron, the grid-based UI we use for generators, developed by me and designed by Egor Alexeev from JB, given its structure could be defined both in JSON or Dhall, and iterpreted and rendered in Elm.

  - [[https://www.youtube.com/watch?v=5mOT5q8SKDM][Video]]  (EN)

*** Generative Animation in Elm


w/Sergey Golovatschov

in 2019

@ [[https://www.youtube.com/playlist?list=PLpVeA1tdgfCCCAKy8DD1SJJ85mOB2ss3l][f(by) '19]]. Minsk, Belarus

How we developed one of our splash screen generators for JetBrains in Elm language by making it manipulate WebGL shaders.

  - [[https://speakerdeck.com/shamansir/generating-animation-with-elm][Slides]]  (EN)

  - [[https://www.youtube.com/watch?v=he1t3uXvl7o][Video]]  (EN)

*** The Future of Web UI Development.


September 2018

@ [[https://www.meetup.com/de-DE/munich-frontend-developers/events/253679780/][FrontEnd Developers Meetup]]. Munich, Germany

Nothing less, nothing more, how I think we are going in the direction of using pure functional programming in the web.

  - [[https://speakerdeck.com/shamansir/the-future-of-web-ui-development][Slides]]  (EN)

*** iElm @ JetBrains


January 2017

Munich, Germany

JetBrains GmbH

The technology behind the notebook REPL iElm (see the previous talk), mostly regarding reverse binary engineering I had to perform to dig out type information from Elm internals.

  - [[https://speakerdeck.com/shamansir/ielm-tech-jb][Slides]]  (EN)

  - [[https://vimeo.com/242822314][iElm in action]]  (EN)

*** iElm


December 2017

Munich, Germany

iElm is a web notebook-like REPL I developed for the Elm language so that it would be easier to learn it with having visual help of both its type system and values show even when they have complex visual representation like canvas graphics. The talk is a poem though.

  - [[https://speakerdeck.com/shamansir/ielm][Slides]]  (EN)

  - [[https://vimeo.com/242822314][iElm in action]]  (EN)

*** Elm. The language itself and how it brings functional programming into web


September 2017

@ [[https://www.meetup.com/de-DE/munich-frontend-developers/events/241139489/][Frontend Developers Meetup]]. Munich, Germany

The syntax of Elm language, its benefits and downfalls. Not the talk I am proud of.

  - [[https://speakerdeck.com/shamansir/elm-revolution][Slides]]  (EN)

  - [[https://www.youtube.com/watch?v=-3OL8V7Lk-Y][Video]]  (EN)

*** About Git. That's easy
(Про Гит. Вот так просто)

in 2017

Munich, Germany

JetBrains GmbH

The details of how the Git command line interface works with the interactive example of rebasing, as well describing other merging techniques.

  - [[https://speakerdeck.com/shamansir/pro-git][Slides (ru)]]  (RU)

*** Elm: 2D & 3D Graphics.


June 2017

@ [[https://www.meetup.com/munich-frontend-developers/][Frontend Developers Meetup]]. Munich, Germany

How the new, and easy-to-learn, functional language for web, named Elm, brings the simple matchematical ways to do both 2D and 3D graphics in Web.

  - [[https://speakerdeck.com/shamansir/elm-2d-and-3d-graphics][Slides]]  (EN)

  - [[https://vimeo.com/manage/videos/222331979][Video]]  (EN)

*** RPD: Reactive Patch Development v2.0


February 2017

@ [[https://www.meetup.com/munichjs-user-group/events/237146815/][JavaScript Meetup]]. Munich, Germany

Google

The slightly extended version of the talk about my visual programming project RPD

  - [[https://speakerdeck.com/shamansir/rpd-reactive-patch-development-extended-cut][Slides @ Google Meetup 2017]]  (EN)

*** RPD: Reactive Patch Development


in 2016

@ [[https://kaiser.gallery/events/js-kongress-2016/][JS Kongress]]. Munich, Germany

15-minute Lightning Talk about the visual programming project I developed in JavaScript, driven by reactive programming concepts (i.e. event streams).

  - [[https://speakerdeck.com/shamansir/rpd-reactive-patch-development][Slides @ JS Kongress 2016]]  (EN)

  - [[https://www.youtube.com/watch?v=K6KDDGlTGqc][Video @ JS Kongress 2016]]  (EN)

*** Animatron Player API in Details


November 2013

@ Ultracode Munich Meetup _#4. Munich, Germany

Wayra GmbH

The details of how API of the Animatron JS Player is desined, with history, examples and sandbox demonstration.

  - [[https://speakerdeck.com/shamansir/animatron-player-api-in-details-v3][Slides, v.3]]  (EN)

  - [[https://vimeo.com/manage/videos/79683081][Video]]  (EN)

*** How to Grasp the Functional Way of Writing JavaScript
(Постигаем функциональный JavaScript)

in 2012

@ Meetup @ e-legion. St. Petersburg, Russia

Discover functional approach in JavaScript as opposed to trying to apply Object-Oriented approach in non-friendly circumstances.

  - [[https://speakerdeck.com/shamansir/postighaiem-funktsional-nyi-javascript][Slides (ru)]]  (RU)
  - [[https://speakerdeck.com/shamansir/mastering-functional-javascript][Slides (en)]]  (EN)

*** The Real JavaScript
(Настоящий JavaScript)

October 2011

@ [[https://dou.ua/calendar/983/][Web Standards Days]]. Kyiv, Ukraine

Putting a stop in the discussion of prototype inheritance in JavaScript with the only best approach possible. Just kidding, it's not possible, but I wanted to share my findings. Be aware: contains octocats and penguidogs.

  - [[https://speakerdeck.com/shamansir/pravil-nyi-javascript][Slides]]  (RU)

  - [[https://vimeo.com/33393795][Video]]  (RU)

*** Fluxus


April 2011

@ [[https://addconf.ru/en/program/12587][Application Developer Days (ADD)]]. St. Peterburg, Russia

Fluxus is the visual tool for developing interactive three-dimensional visuals, for example to react on music. It uses Scheme / Racket stack over OpenGL backend. This talk shares my inspiration with it and demonstrates features of the engine. However, my Jack (not a person, but audio Linux driver) failed at the time of talk, so there was no audio to rely on.

  - [[https://vimeo.com/23468113][Video]]  (RU)

*** Web-development with GWT & mvp4g
(Веб-разработка на GWT и mvp4g)

April 2011

@ [[https://addconf.ru/en/program/12587][Application Developer Days (ADD)]]. St. Peterburg, Russia

The huge (but as fun as possible) talk in three parts on how you could architect your own GWT application using mvp4 framework which simplifies many process and routing. Contains a story of how we did it at iPark.

  - [[https://speakerdeck.com/shamansir/gwt-mvp4g][Slides]]  (RU)

  - [[https://vimeo.com/26357352][Video, p.1/3]]  (RU)
  - [[https://vimeo.com/26413549][Video, p.2/3]]  (RU)
  - [[https://vimeo.com/26715073][Video, p.3/3]]  (RU)

** Projects

  - *Noodle*

Visual Programming for producing Generative Art and more, with CLI & Web & VR (planned) frot-ends, written in PureScript

/Status:/ Almost Finished (at least looks like it)

/Started:/ more than five years ago

([[https://github.com/shamansir/noodle][GH:noodle]], [[https://noodle.labs.jb.gg/][Last working Noodle Demo]])

/Tags:/ #purescript, #visual-programming, #functional-programming, #generative-art


  - *RPD*

Visual Programming for Generative Art, in JavaScript, driven by Reactive Streams Programming

/Status:/ Finished (to some point)

/Started:/ more than ten years ago

([[https://github.com/shamansir/rpd][GH:rpd]], [[https://shamansir.github.io/rpd][RPD Docs & Demos]])

/Tags:/ #javascript, #svg, #visual-programming, #generative-art, #reactive-programming, #kefir.js, #computational-arts


  - *Tron GUI*

Innovative approach for generative art User Interfaces: now grid-based

/Status:/ Finished (to some point)

/Started:/ around two-three years ago

([[https://github.com/shamansir/tron-gui][GH:tron-gui]], [[https://tron.labs.jb.gg/][Tron Constructor @ CAI]], [[https://cai.jetbrains.com/][Computational Arts Initiative]], [[https://tiler.labs.jb.gg/][Tiler @ CAI usage example]], [[https://neobeam.labs.jb.gg/][Neobeam @ CAI usage example]], [[https://plasmatic.labs.jb.gg/][Plasmatic @ CAI usage example]])

/Tags:/ #elm, #gui, #user-interface, #functional-programming, #dhall, #javascript, #generative-art, #computational-arts, #graphs


  - *Kvant*

Translating Wave Function Collapse algorithm to Elm, and UI for it

/Status:/ Stagnated (started, may be accomplished smth, but wasn't finished for a long time)

/Started:/ around four-five years ago

([[https://github.com/shamansir/kvant][GH:kvant]], [[https://kvant.labs.jb.gg/][Kvant Demo @ CAI]], [[https://cai.jetbrains.com/][Computational Arts Initiative]])

/Tags:/ #elm, #gui, #generative-art, #functional-programming, #computational-arts


  - *iElm*

Interactive Visual REPL for Elm language, showing types and SVG and even `elm-canvas` Graphics

/Status:/ Finished (to some point)

/Started:/ around four-five years ago

([[https://github.com/shamansir/ielm][GH:ielm]])

/Tags:/ #elm, #repl, #functional-programming


  - *node-elm-repl*

CLI client for iElm to get the information about the type of the entered expression

/Status:/ Finished (to some point)

/Started:/ around four-five years ago

([[https://github.com/shamansir/node-elm-repl][GH:node-elm-repl]])

/Tags:/ #elm, #javasript, #binary, #repl, #functional-programming


  - *purescript-blessed*

Port of JavaScript Blessed library, which is the powerful window management and component library for Command-Line-interfaces (CLI)

/Status:/ Almost Finished (at least looks like it) (Library)

/Started:/ during last year

([[https://github.com/shamansir/purescript-blessed][GH:purescript-blessed]])

/Tags:/ #cli, #functional-programming, #purescript, #user-interface, #components


  - *Purs-Typeclasses*

The auto-generated interactive SVG poster / Web App of the PureScript TypeClasses' structure and methods and dependencies

/Status:/ Finished (to some point)

/Started:/ around two-three years ago

([[https://github.com/shamansir/purescript-typeclasses][GH:purescript-typeclasses]], [[https://x.com/shaman_sir/status/962696001139232768][Twitter post with sources, v.1]], [[https://x.com/shaman_sir/status/1027968186979950592][Twitter post with sources, v.2]])

/Tags:/ #functional-programming, #purescript, #svg


  - *WinniPeg*

Visual aid and editor for implementing PEG grammars (purescript-grammar) in PureScript

/Status:/ Just Started

/Started:/ during last year

([[https://github.com/shamansir/winni-peg][GH:winni-peg]], [[https://github.com/shamansir/purescript-grammar][GH:purescript-grammar]])

/Tags:/ #functional-programming, #purescript, #org-mode, #peg, #grammars, #parsing, #datalog


  - *&ndORG*

An attempt to develop a user-friendly web ORG-mode editor while conversing most of its `emacs` profits and build UI on visual-keystrokes-concept

/Status:/ Draft

/Started:/ during last year

([[https://github.com/shamansir/ndorg][GH:ndorg]])

/Tags:/ #functional-programming, #purescript, #org-mode, #grammars, #parsing


  - *GEN UI Lang*

On storing UI components definitions for Generative Art in JSON or D-Hall format, for Tron GUI mostly

/Status:/ Stagnated (started, may be accomplished smth, but wasn't finished for a long time)

/Started:/ around two-three years ago

([[https://github.com/shamansir/gen-ui][GH:gen-ui]])

/Tags:/ #elm, #dhall, #gui, #functional-programming, #computational-arts


  - *JS Player for Animatron*



/Status:/ Finished (to some point)

/Started:/ more than five years ago

([[https://github.com/shamansir/animatron-player][GH:animatron-player]])

/Tags:/ #javascript, #canvas, #animation


  - *Web PD: PureData for Web*



/Status:/ Stagnated (started, may be accomplished smth, but wasn't finished for a long time)

/Started:/ more than five years ago

([[https://github.com/shamansir/web-pd][GH:web-pd]])

/Tags:/ #javascript, #pure-data, #svg, #audio-generation, #visual-programming


  - *JetBrains Splash Screen Generator, with RPD*



/Status:/ Finished (to some point)

/Started:/ more than five years ago

([[https://github.com/shamansir/jb-rpd-splash][GH:jb-rpd-splash]], [[https://seti.labs.jb.gg/][SETI Generator in Action @ CAI]], [[https://cai.jetbrains.com/][Computational Arts Initiative]])

/Tags:/ #javascript, #visual-programming, #computational-arts, #glsl, #shaders


  - *sametimed*

The Chat with Friedly-UI based on Google Federation One (a.k.a. Google Wave) protocol

/Status:/ Finished (to some point)

/Started:/ more than ten years ago

([[https://github.com/shamansir/sametimed][GH:sametimed]])

/Tags:/ #java, #google-wave


  - *nijiato*

Finger-recognition in LISP with OpenCV

/Status:/ Finished (to some point)

/Started:/ more than ten years ago

([[https://github.com/shamansir/nijiato][GH:nijiato]])

/Tags:/ #lisp, #camera-tracking, #opencv


  - *My TouchDesigner VJing sources*



/Status:/ Finished (to some point)

/Started:/ around two-three years ago

([[https://github.com/shamansir/touchdesigner][GH:touchdesigner]])

/Tags:/ #touchdesigner, #visuals


  - *Open Radiant*

One of the first art generators for JetBrains

/Status:/ Finished (to some point)

/Started:/ around four-five years ago

([[https://github.com/shamansir/open-radiant][GH:open-radiant]], [[https://cai.jetbrains.com/][Computational Arts Initiative]])

/Tags:/ #elm, #functional-programming, #computational-arts, #generative-art


  - *Open Elmsfeuer*

Another one of the first art generators for JetBrains

/Status:/ Finished (to some point)

/Started:/ around four-five years ago

([[https://github.com/shamansir/open-elmsfeuer][GH:open-elmsfeuer]], [[https://origami.labs.jb.gg/][Origami Generator in Action @ CAI]])

/Tags:/ #elm, #functional-programming, #computational-arts, #generative-art


  - *PegJS - FN*

The concept of functional PEG-driven parsers for JavaScript where every grammar rule is represented with a single pure function

/Status:/ Finished (to some point)

/Started:/ more than five years ago

([[https://github.com/shamansir/pegjs-fn][GH:pegjs-fn]], [[https://shamansir.github.io/pegjs-fn/][PegJS-Fn Playground]])

/Tags:/ #javascript, #functional-programming, #parsing, #grammar


  - *JavaScript Gardern*



/Status:/ Finished (to some point)

/Started:/ more than ten years ago

([[https://github.com/shamansir/javascript-garden][GH:javascript-garden]])

/Tags:/ #javascript, #translation


  - *Japanese Language Reference in Russian*

(PDF, 300+ pages)

/Status:/ Finished (to some point)

/Started:/ more than 20 years ago



/Tags:/ #japanese, #pdf, #translation


  - *Python 3.5 (RU)*

Translating Python 3.5 Reference @ Wikibooks

/Status:/ Finished (to some point)

/Started:/ more than 15 years ago



/Tags:/ #python, #translation


  - *PDF version for how-to-livecode Book*

Laying out PDF for how-to-livecode book

/Status:/ Finished (to some point)

/Started:/ more than five years ago



/Tags:/ #pdf, #generative-audio


  - *purescript-doc*



/Status:/ Almost Finished (at least looks like it) (Library)

/Started:/ during last year

([[https://github.com/shamansir/purescript-doc][GH:purescript-doc]])

/Tags:/ #functional-programming, #purescript, #org-mode, #markdown


  - *purescript-org*



/Status:/ In progress (Library)

/Started:/ during last year

([[https://github.com/shamansir/purescript-org][GH:purescript-org]])

/Tags:/ #functional-programming, #purescript, #org-mode


  - *purescript-grammar*



/Status:/ In progress (Library)

/Started:/ during last year

([[https://github.com/shamansir/purescript-grammar][GH:purescript-grammar]])

/Tags:/ #functional-programming, #purescript, #grammar, #parsing, #datalog


  - *purescript-flex-layout*



/Status:/ In progress (Library)

/Started:/ around two-three years ago

([[https://github.com/shamansir/purescript-flex-layout][GH:purescript-flex-layout]])

/Tags:/ #functional-programming, #purescript, #bin-packing, #user-interface


  - *Finite State Machine engine+example for PureScript*



/Status:/ Finished (to some point) (Library)

/Started:/ around two-three years ago

([[https://github.com/shamansir/purescript-fsm][GH:purescript-fsm]])

/Tags:/ #functional-programming, #purescript, #user-interface


  - *purescript-optics-interactive*

An attempt to demonstrate visually and interactively how Profunctor Optics work in Functional Languages like PureScript (mostly for my own self)

/Status:/ Draft

/Started:/ around two-three years ago

([[https://github.com/shamansir/purescript-optics-interactive][GH:purescript-optics-interactive]])

/Tags:/ #functional-programming, #purescript


  - *purescript-yoga-tree-utils*



/Status:/ Finished (to some point) (Library)

/Started:/ during last year

([[https://github.com/shamansir/purescript-yoga-tree-utils][GH:purescript-yoga-tree-utils]])

/Tags:/ #functional-programming, #purescript, #org-mode


  - *purescript-mahjong*



/Status:/ Draft

/Started:/ around one-two years ago

([[https://github.com/shamansir/purescript-mahjong][GH:purescript-mahjong]])

/Tags:/ #functional-programming, #purescript, #mahjong, #game


  - *PrimCivile*



/Status:/ Draft

/Started:/ around two-three years ago

([[https://github.com/shamansir/primcivile][GH:primcivile]])

/Tags:/ #purescript, #functional-programming, #game


  - *Elm Symbolic Logic Game*



/Status:/ Stagnated (started, may be accomplished smth, but wasn't finished for a long time)

/Started:/ around two-three years ago

([[https://github.com/shamansir/elm-symbolic-logic][GH:elm-symbolic-logic]])

/Tags:/ #elm, #logic, #lewis-carrol, #game


  - *Cayley Rust*



/Status:/ Stagnated (started, may be accomplished smth, but wasn't finished for a long time) (Library)

/Started:/ more than ten years ago

([[https://github.com/shamansir/cayley-rust][GH:cayley-rust]])

/Tags:/ #rust, #graphs, #database


  - *Vimeoid*



/Status:/ Stagnated (started, may be accomplished smth, but wasn't finished for a long time)

/Started:/ more than ten years ago

([[https://github.com/shamansir/vimeoid][GH:vimeoid]])

/Tags:/ #android, #java, #application


  - *NodeJS Binary Parser*



/Started:/ more than ten years ago

([[https://github.com/shamansir/nodejs-binary-parser][GH:nodejs-binary-parser]])


  - *Elm Goose Driven Tutorial*



/Started:/ around four-five years ago

([[https://github.com/shamansir/elm-goose-driven-tutorial][GH:elm-goose-driven-tutorial]])


  - *Showdown Blog*

Blog engine driven by JavaScript + XSLT

/Started:/ more than ten years ago

([[https://github.com/shamansir/showdown-blog][GH:showdown-blog]])


  - *Мюнхен-Флю*



/Started:/ more than five years ago




  - *Лё Баналь*



/Started:/ around four-five years ago




  - *Translation for Duke Nukem 3D Build Engine Tutorial*



/Started:/ more than 20 years ago




  - *The Neverhood Walhthrough*



/Started:/ more than 20 years ago




  - *Transit Maps*



/Started:/ more than five years ago

([[https://github.com/shamansir/transit-maps][GH:transit-maps]])


  - *LEAN Train*



/Started:/ during last year

([[https://github.com/shamansir/lean-train][GH:lean-train]])


  - *Elm Fluxus*



/Started:/ more than five years ago

([[https://github.com/shamansir/elm-fluxus][GH:elm-fluxus]])


  - *Elm Graph Render*



/Started:/ around two-three years ago

([[https://github.com/shamansir/elm-graph-render][GH:elm-graph-render]])


  - *elm-bin-pack*



/Started:/ around two-three years ago

([[https://github.com/shamansir/elm-bin-pack][GH:elm-bin-pack]])


  - *Forster*



/Started:/ more than five years ago

([[https://github.com/shamansir/forster][GH:forster]])


  - *Dat Org Editor*



([[https://github.com/shamansir/dat-org-editor][GH:dat-org-editor]])


  - *Elm-Graph-Render*



([[https://github.com/shamansir/elm-graph-render][GH:elm-graph-render]])


  - *Exercism*



/Started:/ more than five years ago

([[https://github.com/shamansir/exercism][GH:exercism]])


  - *Elm-Friendly-Parser*



([[https://github.com/shamansir/elm-friendly-parser][GH:elm-friendly-parser]])


  - *Track-Me-I-Am-Famous*



([[https://github.com/shamansir/track-me-i-am-famous][GH:track-me-i-am-famous]])


  - *Elm-Ohm-Grammar*



([[https://github.com/shamansir/elm-ohm-grammar][GH:elm-ohm-grammar]])


  - *RPD-P5-Particle-System*



([[https://github.com/shamansir/rpd-p5-particle-system][GH:rpd-p5-particle-system]])


  - *RPD-PureData*



/Started:/ more than five years ago

([[https://github.com/shamansir/rpd-puredata][GH:rpd-puredata]])


  - *Showdown-Blog*



([[https://github.com/shamansir/showdown-blog][GH:showdown-blog]])


  - *Mdown-Parse-PegJS*



([[https://github.com/shamansir/mdown-parse-pegjs][GH:mdown-parse-pegjs]])


  - *XTD (forall-TD)*



([[https://github.com/shamansir/xtd][GH:xtd]])


  - *GWT-mvp4-layouting-demo*



([[https://github.com/shamansir/gwt-mvp4-layouting-demo][GH:gwt-mvp4-layouting-demo]])


  - *Fluxus-music-demo-addconf*



([[https://github.com/shamansir/fluxus-music-demo-addconf][GH:fluxus-music-demo-addconf]])


  - *Cometd-Demo*



/Started:/ more than 15 years ago

([[https://github.com/shamansir/cometd-demo][GH:cometd-demo]])


  - *Corsika-Visualization*



([[https://github.com/shamansir/corsika-visualization][GH:corsika-visualization]])

