#+title: Eric IDE 4.0.1 in Ubuntu 7.04
#+publishDate: <2007-07-22T18:05>
#+tags: eric-ide python ubuntu
#+hugo_section: blog-en
#+author: Anton Kotenko

[[http://www.die-offenbachs.de/eric/index.html][Eric]] -- is very good
IDE for [[http://www.python.org/][Python]]. And
[[http://www.die-offenbachs.de/eric/eric-news.html][just yesterday]] the
new
[[http://sourceforge.net/project/showfiles.php?group_id=119070&package_id=233329][4.0.1]]
version was released, but in repositories the last version for the
moment is 3.9, and I found myself missing those good old times when I've
compiled packages form sources recently. So I am presenting you a
listing of things to be done just in case, to prevent you from meeting
the errors that visited me through the process of compilation. Something
from this stuff is oriented on new versions :). Just because it was
installed on clean Ubuntu - everything must be adequate... If I missed
something, please report.

/What is used:/

- [[http://www.die-offenbachs.de/eric/index.html][eric]] 4.0.0.1
- [[http://www.python.org/][Python]] 2.5.1
- [[http://trolltech.com/products/qt][Qt]] 4.2.3 +
  [[http://www.riverbankcomputing.co.uk/pyqt/index.php][PyQt]] v4.1 +
  [[http://www.riverbankcomputing.co.uk/qscintilla/index.php][QScintilla]]
  2
- [[http://www.riverbankcomputing.co.uk/sip/index.php][SIP]] 4.6
- [[http://gcc.gnu.org/][G++]] 3.4 (I almost sure you may take the
  latest one)

so, let's go into some catalogue for compilation and start:

#+begin_example
$ cd ~/distr-temp/
#+end_example

using
[[http://sourceforge.net/project/showfiles.php?group_id=119070&package_id=233329][sources]]
from sourceforge:

#+begin_example
$ wget http://mesh.dl.sourceforge.net/sourceforge/eric-ide/eric4-4.0.1.tar.gz
#+end_example

we will install different libraries for
[[http://www.riverbankcomputing.co.uk/pyqt/index.php][PyQt]] (depending
of =apt-get= settings you may need an install CD):

#+begin_example
$ sudo apt-get install python2.5-dev
$ sudo apt-get install python-qt4
$ sudo apt-get install libqt4-dev
$ sudo apt-get install python-qt4-dev
#+end_example

then we'll install =g++= compiler and make a =/usr/bin/g++= link:

#+begin_example
$ sudo apt-get install g++-3.4
$ sudo ln -s /usr/bin/g++-3.4 /usr/bin/g++
#+end_example

then download and install the last current version of
[[http://www.riverbankcomputing.co.uk/sip/index.php][SIP]] -- it allows
the libraries written C[++] to act themselves as
[[http://www.python.org/][Python]] modules:

#+begin_example
$ wget http://www.riverbankcomputing.com/Downloads/sip4/sip-4.6.tar.gz
$ tar -xvzf ./sip-4.6.tar.gz
$ cd ./sip-4.6.tar.gz
$ python ./configure.py
$ make
$ sudo make install
$ cd ..
#+end_example

then download and install the last current version of
[[http://www.riverbankcomputing.co.uk/qscintilla/index.php][QScintilla]]
-- Qt-port for source code editor component (version is for Qt4):

#+begin_example
$ wget http://www.riverbankcomputing.com/Downloads/ \
  Snapshots/QScintilla2/QScintilla-gpl-2-snapshot-20070709.tar.gz
$ tar -xvzf ./QScintilla-gpl-2-snapshot-20070709.tar.gz
$ cd ./QScintilla-gpl-2-snapshot-20070709/Qt4
$ qmake qscintilla.pro
$ sudo make
$ sudo make install
#+end_example

now we need to install bindings of
[[http://www.riverbankcomputing.co.uk/qscintilla/index.php][QScintilla]]
for [[http://www.python.org/][Python]] -- they are placed in =Python=
directory:

#+begin_example
$ cd ../Python
$ python ./configure.py
$ make
$ sudo make install
#+end_example

and finally the [[http://www.die-offenbachs.de/eric/index.html][eric]]'s
turn:

#+begin_example
$ cd ../../eric4-4.0.1/
$ sudo python install.py
#+end_example

when installing, you need to specify the directory where Qt lies:
=/usr/share/qt4=.

Well, actually that's all. You can type =eric4= and make fun, if you
want :).
