#+title: Occasional Textpattern Bug
#+datetime: 23 Jul 2007 02:14
#+tags: php textpattern

While I've played with [[http://textpattern.org/][textpattern]] at
[[http://sharedcode.info/][sharecode]], I faced this issue that may come
in touch with those who uses [[http://textpattern.org/][textpattern]].

I was frightened with the fact that commenting support in articles which
were written too long ago was expired. I've searched over all of the
preferences - nothing about this - but it is almost obvious that it must
be. The good thing is that I've googled and found the
[[http://hari.literaryforums.org/2007/04/22/textpattern-review/][post]],
and through its comments I've reached the
[[http://textpattern.com/faq/257/comment-preferences-are-missing][FAQ
article]].

The mean is if in your /Admin/ -> /Preferences/ -> /Basic/ page for
/Comments/ section you see only two points (and you have 4.0.4 version
and no wish/ossibility to update currently) -- this article is for you.

You need to do just two actions. First - take
=./textpattern/include/txp_prefs.php= file from your hosting, find a 89
line:

#+begin_src php

$evt_list = safe_column('event', 'txp_prefs',
     "type = 0 and prefs_id = 1 group by 'event' order by event desc");
#+end_src

and to delete the quotes wrapping =event= to make it match with
[[http://dev.textpattern.com/browser/development/4.0/textpattern/include/txp_prefs.php?rev=2156#L89][this
variant]]):

#+begin_src php

$evt_list = safe_column('event', 'txp_prefs',
     "type = 0 and prefs_id = 1 group by event order by event desc");
#+end_src

second -- redeploy the file back. Finita la comedia -- you're welcome in
preferences, /Comments:Disabled after/.
