#+title: "Do Androids Dream of Generating Art"
#+publishDate: <2020-01-04T10:15>
#+hugo_section: blog/drafts

Indeed, it turned out that that is actually is one of their basic innate
core dreams. We have launched a huge and complex experiment on the topic
and in the end we're quite satisfied with the results. Just look at some
pictures we are now able to produce inside the post. And those are
definitely not the limit.

But still, those wild unbridled neural networks need some training. They
need digital cowboys and digital cowgirls to train them producing the
results which match our corporate style and/or the style of those who
are training them. So /we need you/!

Just follow the link: [[https://train-jb-limb.labs.jb.gg/]]

Remember, the choices you make are being recorded! But only used to
train the gods inside those surely-non-violent machines.

[[https://lh5.googleusercontent.com/_KAzUT-0COGvGGLl2EILcKXiLhOoJNUomqhqSPMRKx_zt8XQTdnb3Z88eFUrFk_FaN5bqlKoJsjp-tbLA9fOrlxXi408Y6wIz5gBxxjwlIH4bMj0lmTuzs8vPwcn6l8AlPOFJMFE]]

Now, to the details:

First, and the most important: for the moment it is a *prototype* which
we decided to launch anyway, since we'd really like to *train* the
system using *your decisions* before the releases and use the knowledge
we got to create the splash screens for the IDEs.

You need *VPN* to access it from home, please use this article to
configure your VPN connection if you haven't yet:
[[https://confluence.jetbrains.com/pages/viewpage.action?title=VPN+Settings+in+JetBrains&spaceKey=JBINT][VPN
Settings in JetBrains]]

Tested and developed only in *Chrome browser.* /It's a pity/, but of
course we will extend our supported browsers to another ones, just a bit
later.

You'll have *to* *wait*, sometimes a lot, for the system to respond.
Just imagine the neural networks running below there. Yet of course
we're not satisfied with the speed, we already did some preparations to
speed things up, and in next weeks we plan to move it to the
performance-oriented machines and everything should become fast and
smooth. At least much faster and smoother.

/Cool thing:/ Change *product* selection in the sidebar to see how the
resulting palette changes following the product brand colors. *Limb* is
the default product and it does no affection.

/Even cooler thing:/ You may *save* the images and combinations you've
made to restore them later or to send them to a friend. Just hit the
*URL* button when you like what you see and copy it from the address
bar.

Use the *crossbreeding*, like Michurin did: select the samples you like,
press the corresponding button and voilà --- you have produced some new
species.

Actually, *touch all* the controls at the right side. Usually you can
see the effect, rarely you can't, but it's ok, in other configuration
you'll find out what every button or slider means.

*Double-click* the images you like in the grid to try the fine tuning.
When you like the result, click the *URL* button and copy the *URL* to
share it with someone. *Double-click* them again to return back to the
grid mode.

We are segregating the *groups* who teach the system. In the end, we'll
know what designers like and what Ruby programmers like, and we will use
this data to provide them with the things they like. Animation is the
planned feature and so it is important to teach the system now to get
screensavers you'll like in the future.

So we encourage you to *experiment* and don't wait any longer! Only for
images to load, that's what we kindly ask to wait ;).

The people who did it for you and for themselves:

[[https://jetbrains.team/m/Serg][[cite/t:@Serg]]]o Golovachev --- The
ideas, The Elm code, Color Correction;

[[https://jetbrains.team/m/Vladimir.Sotnikov][[cite/t:@Vladimir]
Sotnikov]] --- The Core Neural Networks Engine and the server-side
power;

[[https://jetbrains.team/m/Anthony.Kotenko][[cite/t:@Anton] Kotenko]]
--- The Elm code, The refactorings, some JS also though, both are
frontend power;

[cite/t:@Vadim] Reyder --- The Cluster magic, the Kuber-power;

Feel free to write us personally or join *#computational-arts* in Space
or in Slack.
